#!/bin/bash

if [[ ! -d /var/log/updatem-226 ]]
then
	mkdir /var/log/updatem-226
fi

# preinst script for updatem-226
#
# see: dh_installdeb(1)

# set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package



exit 0
